# Generated by Django 4.1.3 on 2022-11-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=150)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=150)),
                ('curso', models.CharField(choices=[('Curso Técnico', 'Curso Técnico'), ('Curso Integrado', 'Curso Integrado')], max_length=150)),
            ],
        ),
    ]
