# Generated by Django 4.1.3 on 2022-11-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_minicursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='minicursos',
            field=models.ManyToManyField(max_length=200, to='main.minicursos'),
        ),
    ]
